# Generated by Django 6.1 on 2026-08-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_group_visit',
            field=models.BooleanField(default=False, help_text='Check this if multiple visitors are intentionally scheduled to see this host at the same time.'),
        ),
    ]
